language: python
python:
  - "2.7"
  - "2.6"

install:

- pip install -r requirements.txt --use-mirrors

script:
# install scholarec
- sudo /usr/bin/python setup.py install
# test setup.py
- sudo /usr/bin/python setup.py test
# run tests
- ./tests/run-tests.sh

