language: python
python:
  - "2.7"
  - "2.6"

install:

- pip install -r requirements.txt --use-mirrors
# - pip install wikipedia==1.3

script:

# install scholarec
#- pip install -e .
- python setup.py install
# test setup.py
- python setup.py test
# run tests
- ./tests/run-tests.sh
